# TODO: Maybe generate a default database
version: '3.8'
services:
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest
    ports:
      - "${SPEEDTEST_PORT}:80"
    environment:
      - DB_CONNECTION=sqlite
