version: '3.8'
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIME_ZONE}*/*/*/*/*/
      - SERVERURL=${DOMAIN_NAME}
      - PEERS=${WIREGUARD_PEERS}
      # FIXME: This doens't work on iPhone (need to test Windows). May be related to DNS over HTTPS.
      # Breaks DNS resolution on the client. Need to look up how routing works in Wireguard.
      - PEERDNS=${LOCAL_IP}
    volumes:
      - ${DATA_ROOT}/wireguard:/config
    ports:
      - ${WIREGUARD_PORT}:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
