#!/bin/bash

COMPOSE_PROJECT_NAME: self-hosted

# Enable debugging for containers. May want to disable for production
# Don't rely on security through obscurity however
DEBUG: true

CACHE_ROOT: $(pwd)"/cache"
# Change this for a different data location
DATA_ROOT: /mnt/extern/containers/data
LOGS_ROOT: $(pwd)"/logs"
# Change this for a different backup location
BACKUP_REPO: /mnt/extern/containers/backups
SSHKEYS: $(eval echo ~$USER)/.ssh

# NOTE: Most services do not use this, use only for locales, not for languages
LANGUAGE: en_GB

# See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for a list of supported values
TIME_ZONE: Europe/London

# Keep this port order for organisation
HOMEPAGE_PORT: 8006
PAPERLESS_PORT: 8007
JOPLIN_PORT: 8008

IMMICH_PORT: 8010
GITEA_WEB_PORT: 8011
GITEA_SSH_PORT: 8012
FIREFLY_APP_PORT: 8013
FIREFLY_IMPORTER_PORT: 8014
YACHT_PORT: 8015
GLANCES_PORT: 8016
GATUS_PORT: 8017

# TODO: Add the compose for this to the main repo
CHEF_BACKEND_PORT: 3000
CHEF_WEB_PORT: 5173
