---

# Environment variables to export to the containers
# All values will be stringified, so don't worry about types
# Special cases:
# - Arrays will be converted to a comma-separated string

#==============================================================================
# General
#==============================================================================
# Enable debugging for containers. May want to disable for production
# Don't rely on security through obscurity however
DEBUG: "false"

LOCAL_IP: 192.168.0.202

# Maximum response time for a service to be considered healthy, in milliseconds
HEALTH_TIMEOUT: 1000

#==============================================================================
# Paths
#==============================================================================
# Change this for a different data location
DATA_ROOT: /mnt/extern/containers/data
DATA_ROOT_NOBACKUP: /mnt/extern/containers/data-nobackup
# Change this for a different backup location
RESTIC_REPO: /mnt/extern/containers/restic

#==============================================================================
# Locale
#==============================================================================
# NOTE: Most services do not use this, use only for locales, not for languages
LANGUAGE: en_GB

# See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for a list of supported values
TIME_ZONE: Europe/London

#==============================================================================
# Service Versions
#==============================================================================
# The tags of the images to use. I recommend against using `latest` to
# avoid any unexpected changes. What's up Docker will show you the available
# updates for your containers.
IMMICH_VERSION: v1.102.3

MINECRAFT_VERSION: 1.20.4

#==============================================================================
# Service Config
#==============================================================================
# Service configs that are shared between multiple services
# Configs used by only one service are in the service's environent file and compose

#----------------
# SpeedTest
#----------------
# Cron expression to run speed test on.
SPEEDTEST_SCHEDULE: "*/15 * * * *"
# Days to retain speed test results for
SPEEDTEST_RETENTION: 30

#----------------
# Minecraft
#----------------

# Max view distance to send to the client.
# NOTE: This will be loaded for all clients, even if they have a lower view distance set.
MINECRAFT_VIEW_DISTANCE: 16

# Mods to install from Modrinth.
MINECRAFT_MODS:
  - fabric-api # Dependency for other mods
  - bluemap # Map
  - ferrite-core # Saves RAM
  - lithium # Optimises server performance

#==============================================================================
# Ports
#==============================================================================
# Keep this port order for organisation
# TODO: Would be nice to assign these dynamically, but that would require reconfiguring
# nginx every time in case the port changes, and checking for conflicts before assigning (not trivial in nushell)

WUD_PORT: 8009
IMMICH_PORT: 8010
FORGEJO_WEB_PORT: 8011



YACHT_PORT: 8015
GLANCES_PORT: 8016
GATUS_PORT: 8017
JELLYFIN_PORT: 8018
SPEEDTEST_PORT: 8019
PAPERLESS_PORT: 8021

ADGUARD_WEB_PORT: 8023
MINECRAFT_BLUEMAP_PORT: 8024

# TODO: Add the compose for this to the main repo
CHEF_BACKEND_PORT: 3000
CHEF_WEB_PORT: 5173

# Protocols other than HTTP can't be forwarded through the reverse proxy
# so their ports need to be exposed directly
ADGUARD_DNS_PORT: 53
FORGEJO_SSH_PORT: 2022
MINECRAFT_PORT: 25565
WIREGUARD_PORT: 51820
