version: '3.8'

services:
  yacht:
    image: selfhostedpro/yacht:latest
    container_name: yacht
    restart: unless-stopped
    ports:
      - ${YACHT_PORT}:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_ROOT}}/yacht:/config
