version: '3.8'
services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "${ADGUARD_DNS_PORT}:53/tcp"
      - "${ADGUARD_DNS_PORT}:53/udp"
      - "${ADGUARD_WEB_PORT}:80/tcp"
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ${DATA_ROOT}/adguard/work:/opt/adguardhome/work
