version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    user: ${USER_ID}:${GROUP_ID}
    ports:
      - "80:8080"
      - "443:443"
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    volumes:
      # No need to mount local config files, these are baked into the image
      - ${DATA_ROOT}/nginx/certbot/www:/var/www/certbot
      - ${DATA_ROOT}/nginx/certbot/conf:/etc/letsencrypt
      - ${DATA_ROOT}/nginx/static:/var/www/static
      - /home/kieran/portfolio:/var/www/html
    restart: unless-stopped
    command: [nginx, '-g', 'daemon off;']
