version: '3.8'
services:
  nginx:
    image: nginx:1.25.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      # Only mount the main nginx.conf file, don't overwrite the default includes
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      # Provide additional includes in their own directory
      - ./includes:/etc/nginx/includes
      - ${DATA_ROOT}/nginx/certbot/www:/var/www/certbot
      - ${DATA_ROOT}/nginx/certbot/conf:/etc/letsencrypt
      - ${DATA_ROOT}/nginx/static:/var/www/static
    restart: unless-stopped
    command: [nginx, '-g', 'daemon off;']
