version: '3.8'
services:
  nginx:
    image: nginx:1.25.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      - ${DATA_ROOT}/nginx/certbot/www:/var/www/certbot
      - ${DATA_ROOT}/nginx/certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    command: [nginx, '-g', 'daemon off;']
  # This is in the same docker-compose as it needs to share the volumes with nginx
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ${DATA_ROOT}/nginx/certbot/www:/var/www/certbot
      - ${DATA_ROOT}/nginx/certbot/conf:/etc/letsencrypt
