version: '3.8'

services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    # Give access to the host network to show network metrics
    network_mode: host
    volumes:
      # Give access to the Docker socket to show container metrics
      - /var/run/docker.sock:/var/run/docker.sock
      # Read-only access to the host filesystem. Needed to read fs usage
      - /:/host:ro
    environment:
      # Run as a web server
      - GLANCES_OPT=-w --port ${GLANCES_PORT}
