version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - ${DATA_ROOT}/jellyfin/config:/config
      - ${DATA_ROOT}/jellyfin/cache:/cache
      - ${DATA_ROOT}/jellyfin/media:/media
    ports:
      - ${JELLYFIN_PORT}:8096
