version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: ${USER_ID}
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      - ${CACHE_ROOT}/jellyfin:/cache
      - ${DATA_ROOT}/jellyfin/config:/config
      - ${DATA_ROOT_NOBACKUP}/jellyfin/media:/media:ro
