---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Bookmarks:
    - Project Github:
        - icon: github-light
          href: https://github.com/kieranknowles1/selfhosting
          description: This project's Github repository
