---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Productivity:
  - Paperless:
      href: /paperless
      description: Document management system
      icon: paperless
      container: paperless
  - Trilium:
      href: /trilium
      description: Personal knowledge base
      icon: trilium
      container: trilium
