---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

language: en-GB

theme: dark
color: amber
background:
  # NOTE: If changed, please also update the credits in custom.js
  image: https://images.pexels.com/photos/531880/pexels-photo-531880.jpeg

cardBlur: md

statusStyle: dot

layout:
  Server Status:
    icon: mdi-server
    style: row
    columns: 3
  Development:
    icon: mdi-code-braces
  Productivity:
    icon: mdi-briefcase
  Media:
    icon: mdi-camera
  Food:
    icon: mdi-food-drumstick

quickLaunch:
  searchDescriptions: true
