---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

language: en-GB

theme: dark

layout:
  Productivity:
    icon: mdi-briefcase
    style: row
    columns: 2

quickLaunch:
  searchDescriptions: true

showStats: true
