---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

language: en-GB

theme: dark
color: slate

statusStyle: dot

layout:
  Server Status:
    tab: Internet Accessible
    icon: mdi-server
    style: row
    columns: 2
  Development:
    tab: Internet Accessible
    icon: mdi-code-braces
  Productivity:
    tab: Internet Accessible
    icon: mdi-briefcase
    style: row
    columns: 2
  Media:
    tab: Internet Accessible
    icon: mdi-camera

  Administration:
    tab: Local Network Only
    icon: mdi-cogs

quickLaunch:
  searchDescriptions: true
