---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

language: en-GB

theme: dark

layout:
  Development:
    icon: mdi-code-braces
  Productivity:
    icon: mdi-briefcase
    style: row
    columns: 2
  Media:
    icon: mdi-camera

quickLaunch:
  searchDescriptions: true
