---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    # Other metrics are provided by Glances
    # This always returns 0 on my system
    # cputemp: true
    uptime: true

- search:
    provider: google
    target: _blank

- datetime:
    format:
        dateStyle: medium
        timeStyle: short
        hourCycle: h23
