---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    expanded: true
    cpu: true
    memory: true
    # This always returns 0 on my system
    # cputemp: true
    uptime: true
- resources:
    label: Internal Disk
    expanded: true
    disk: /host
- resources:
    label: External Disk
    expanded: true
    disk: /host/mnt/extern

- search:
    provider: google
    target: _blank

- datetime:
    format:
        dateStyle: medium
        timeStyle: short
        hourCycle: h23
