version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    user: ${USER_ID}:${GROUP_ID}
    # Restart on crash, retry 5 times
    restart: on-failure:5
    ports:
      - "${MINECRAFT_PORT}:25565"
      - "${MINECRAFT_BLUEMAP_PORT}:8100"
    volumes:
      - "${DATA_ROOT}/minecraft:/data"
      - ./config:/config
      - type: bind
        source: "./mods.txt"
        target: "/extra/mods.txt"
    environment:
      - TYPE=FABRIC
      - MODS_FILE=/extra/mods.txt
      # Pause the server 1 hour after the last player leaves
      - ENABLE_AUTOPAUSE=true
      - EXISTING_OPS_FILE=SYNCHRONIZE
      - EXISTING_WHITELIST_FILE=SYNCHRONIZE
      # Required to avoid a "tick took too long" crash after a pause
      - MAX_TICK_TIME=-1
      - MOTD=A Minecraft Server Powered by Docker

      # Public user settings, configured in `environment.yml`
      - VIEW_DISTANCE=${MINECRAFT_VIEW_DISTANCE}

      # Secret user settings, configured in `userenv.yml`
      - EULA=${MINECRAFT_EULA}
      - OPS=${MINECRAFT_OPS}
      - WHITELIST=${MINECRAFT_WHITELIST}
      - RESOURCE_PACK=${MINECRAFT_RESOURCE_PACK}
      - RESOURCE_PACK_SHA1=${MINECRAFT_RESOURCE_PACK_SHA1}
