domains:
  - domain: bluemap
    name: Bluemap
    portVar: MINECRAFT_BLUEMAP_PORT
    # Minecraft pauses itself when no one is online, and Bluemap is hosted through the same process
    # TODO: Use an external web server for this to avoid depending on server not being paused
    includeInStatus: false
usesData: true
