version: '3.8'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${LOGS_ROOT}/homepage:/app/config/logs/
      - ./config/:/app/config/:ro
      # For docker status and stats monitoring
      - /var/run/docker.sock:/var/run/docker.sock
      # For disk usage monitoring
      - /:/host:ro
