version: '3.8'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${HOMEPAGE_VERSION}
    container_name: homepage
    restart: unless-stopped
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${LOGS_ROOT}/homepage:/app/config/logs/
      - ./config/:/app/config/
      # For docker status and stats monitoring
      - /var/run/docker.sock:/var/run/docker.sock
