version: '3.8'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${DATA_ROOT}/homepage/logs:/app/config/logs/
      - ./config/:/app/config/:ro
      # For docker
      - /var/run/docker.sock:/var/run/docker.sock
