# See https://github.com/borgmatic-collective/docker-borgmatic/tree/2a56a5b9ba0ee6a9c7806d7123a8d9cd2c63de55#restoring-backups
# for restore instructions
# You will need to run `source .env` and `source .env.user` in the root of this repo before running
# The respository is mounted at /mnt/repo
# The restore directory is mounted at /restore

# TODO: Need to test restore process, for both local and remote backups. Think local
# is working, but only done a ls so far
# =================================================================================================
# MAKE A BACKUP OF THE BACKUP BEFORE RESTORING!
# This has WRITE ACCESS to the backup repository, so it can overwrite your backup!
# =================================================================================================

version: '3.8'
services:
  borgmatic:
    container_name: borg-restore

    cap_add:
      - SYS_ADMIN

    volumes:
      - ./restore:/restore

    security_opt:
      - apparmor:unconfined
      - label:disable

    devices:
      - /dev/fuse:/dev/fuse

    command: /bin/sh
